### ISSUE TITLE
Support negative lookahead and similar

### ISSUE THREAD

**Issue by cool-RR** [thomasschafer/scooter#44]
I tried doing a replace on this: `#!(?!/usr/bin/env python)` and got "Error: Couldn't parse regex". I'm guessing it's because negative lookahead isn't supported.

**Comment by thomasschafer** [comment]
The [regex](https://docs.rs/regex/latest/regex/) library scooter uses doesn't support negative lookahead, which is why you're seeing the error. I think there are other libraries that allow for this so a potential future feature would be to have an additional regex library available for users to use via a CLI flag

**Comment by cool-RR** [comment]
Why not switch to a better regex library as default?

**Comment by cool-RR** [comment]
I see, that makes sense. Another option is to automatically switch to a
different crate when we identify that certain features, like negative
lookahead, are being used.
